### ISSUE TITLE
Todo 앱 필수 기능 구현

### ISSUE THREAD

**Issue by lovelyunsh** [lovelyunsh/java-study-2week#1]
### 공통 조건

1. 일정 작성, 수정, 조회 시 반환 받은 일정 정보에 `비밀번호`는 제외되어 있습니다.
2. 일정 수정, 삭제 시 선택한 일정의 `비밀번호`와 요청할 때 함께 보낸 `비밀번호`가 일치할 경우에만 가능합니다.

### 필수 구현 기능(요구사항)

- [ ]  생성 - 일정 작성
    - [ ]  `할 일 제목`, `할 일 내용`, `담당자`, `비밀번호`, `작성일` 을 저장할 수 있습니다.
        - [ ]  저장된 일정 정보를 반환 받아 확인할 수 있습니다.
- [ ]  조회 - 선택한 일정 조회(상세 페이지)
    - [ ]  선택한 일정의 정보를 조회할 수 있습니다.
    - [ ]  반환 받은 일정 정보에는 `할 일 제목`,`할 일 내용`, `작성일`, `작성자 이름` 정보가 들어있습니다.
- [ ]  조회 - 일정 목록 조회
    - [ ]  등록된 일정 전체를 조회할 수 있습니다.
    - [ ]  조회된 일정 목록은 `작성일` 기준 내림차순으로 정렬 되어있습니다.
- [ ]  수정 - 선택한 일정 수정
    - [ ]  선택한 일정의 `할 일 제목`, `할 일 내용`, `담당자`를 수정할 수 있습니다.
    - [ ]  서버에 일정 수정을 요청할 때 `비밀번호`를 함께 전달합니다.
        - [ ]  생성 시에, 입력한 비밀번호와 일치할 경우에만 수정할 수 있습니다.
    - [ ]  수정된 일정의 정보를 반환 받아 확인할 수 있습니다.
- [ ]  삭제 - 선택한 일정 삭제
    - [ ]  서버에 일정 삭제를 요청할 때 `비밀번호`를 함께 전달합니다.
        - [ ]  생성 시에, 입력한 비밀번호와 일치할 경우에만 수정할 수 있습니다.
